/**
 * Better Auth configuration and utilities
 * T011: Updated with JWT plugin (EdDSA/Ed25519 algorithm)
 * T020: UUID auto-generated by database and included in JWT
 */
import { betterAuth } from "better-auth";
import { jwt } from "better-auth/plugins";
import { Pool } from "pg";

// Create PostgreSQL connection pool
const pool = new Pool({
  connectionString: process.env.DATABASE_URL!,
});

// Initialize Better Auth with JWT plugin (T011) and UUID generation (T020)
export const auth = betterAuth({
  database: pool,
  emailAndPassword: {
    enabled: true,
    requireEmailVerification: false, // Phase II: Disabled for simplicity
  },
  secret: process.env.BETTER_AUTH_SECRET!,
  baseURL: process.env.NEXT_PUBLIC_APP_URL || "http://localhost:3000",
  session: {
    expiresIn: 60 * 60 * 24 * 7, // 7 days
    updateAge: 60 * 60 * 24, // 1 day
    cookieCache: {
      enabled: true,
      maxAge: 60 * 5, // 5 minutes
    },
  },
  advanced: {
    cookiePrefix: "todo_auth",
    useSecureCookies: process.env.NODE_ENV === "production",
  },
  // T011: JWT plugin with EdDSA/Ed25519 algorithm (better-auth-fastapi-jwt-bridge pattern)
  // T020: Extended to include UUID in JWT payload
  plugins: [
    jwt({
      algorithm: "EdDSA", // Ed25519 for faster verification (10-20x faster than RS256)
      issuer: process.env.NEXT_PUBLIC_APP_URL || "http://localhost:3000",
      expiresIn: "1h", // Token expiration (default: 1 hour)
      jwks: {
        enabled: true, // Enable JWKS endpoint at /.well-known/jwks.json
      },
      // T020: Include UUID in JWT payload for backend API use
      async jwt(user, session) {
        // Fetch UUID from database (since it's not loaded by default)
        // T085: Don't log PII (user IDs) in production
        console.log("[Better Auth JWT] Generating JWT for user (ID present):", !!user.id);
        const result = await pool.query(
          'SELECT uuid FROM "user" WHERE id = $1',
          [user.id]
        );

        const uuid = result.rows[0]?.uuid;
        // T085: Don't log PII (UUIDs) in production
        console.log("[Better Auth JWT] UUID fetched from database:", !!uuid);

        return {
          uuid, // Include UUID in JWT token
        };
      },
    }),
  ],
  // T020: Fetch UUID after user creation (generated by database default)
  hooks: {
    user: {
      created: async ({ user }) => {
        // Fetch the UUID that was auto-generated by database server_default
        const result = await pool.query(
          'SELECT uuid FROM "user" WHERE id = $1',
          [user.id]
        );

        const uuid = result.rows[0]?.uuid;

        // Return updated user object with UUID for session
        return {
          ...user,
          uuid,
        };
      },
    },
    session: {
      created: async ({ session, user }) => {
        // Fetch UUID for every new session (login)
        const result = await pool.query(
          'SELECT uuid FROM "user" WHERE id = $1',
          [user.id]
        );

        const uuid = result.rows[0]?.uuid;

        // Add UUID to session for frontend access
        return {
          ...session,
          user: {
            ...session.user,
            uuid,
          },
        };
      },
    },
  },
});

/**
 * Get current session on the server side
 */
export async function getSession() {
  return await auth.api.getSession({
    headers: await import("next/headers").then((mod) => mod.headers()),
  });
}

/**
 * Sign out helper function
 */
export async function signOut() {
  await auth.api.signOut({
    headers: await import("next/headers").then((mod) => mod.headers()),
  });
}
